version: "3.9"

services:
  
  api:
    build: .
    ports:
      - "9000:9000"
    command: uvicorn telegram_bot.app:app --workers 4 --host=0.0.0.0 --port=9000 --env-file=.env
    volumes:
      - ./telegram_bot:/telegram_bot
    environment:
      - DOMAIN=xxx
      - CACHE_TTL=3540
    depends_on:
      - redis
      - database

  redis:
    image: redis:latest

  database:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=alpha
    ports:
      - "5432:5432"
    user: postgres

volumes:
  postgres_data:
