version: "3.9"

services:

  api:
    build: ./telegram_bot
    ports:
      - "9000:9000"
    command: uvicorn app:app --workers 4 --host=0.0.0.0 
    volumes:
      - ./telegram_bot:/app
    environment:
      - DOMAIN=xxx
      - CACHE_TTL=3540
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=alpha
    ports:
      - "5432:5432"
    user: postgres

volumes:
  postgres_data:
